lowestYNormalCustom: -30
highestYNormalCustom: 280
lowestYNether: 4
highestYNether: 120
lowestYEnd: 0
highestYEnd: 320
normalCustomAirBuildingMinAltitude: 80
normalCustomAirBuildingMaxAltitude: 120
endAirBuildMinAltitude: 80
endAirBuildMaxAltitude: 120
warnAdminsAboutNewBuildings: false
regionProtectedMessage: '&8[BetterStructures] &cDefeat the zone''s bosses to edit
  blocks!'
protectEliteMobsRegions: true
setupDone: false
modularChunkPastingSpeed: 20
# Sets the maximum percentage of a tick that BetterStructures will use to paste builds, however many it maybe trying to generate.
# Ranges from 0.01 to 1, where 0.01 is 1% and 1 is 100%.
# Slower speeds will lower performance impact, but can lead to other problems such as builds suddenly popping in.
percentageOfTickUsedForPasting: 0.4
distanceSurface: 20
distanceShallow: 15
distanceDeep: 15
distanceSky: 60
distanceLiquid: 40
maxOffsetSurface: 2
maxOffsetShallow: 2
maxOffsetDeep: 2
maxOffsetSky: 2
maxOffsetLiquid: 2
